services:
  - type: web
    name: shopaudit
    env: node
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node dist/http-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    healthCheckPath: /health
    autoDeploy: true 
